##
## EPITECH PROJECT, 2023
## chocolatine
## File description:
## First use of github workflow
##

name: chocolatine

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: git@github.com:EpitechPromo2028/B-DOP-200-NAN-2-1-chocolatine-matisse.marsac.git
  EXECUTABLES: a.out

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: checkout-v4
        uses: actions/checkout@v4
      - name: run-coding-style
        run: check.sh $(pwd) $(pwd)
      - name: check_any_error
        run: |
          cat coding-style-reports.log | while read line; do
            TYPE=$(echo $line | cut -d ':' -f 3 | cut -c 2-)
            temp=$(echo $line | cut -d ':' -f 1)
            NAME=$(echo $temp | cut -d '/' -f 2)
            LINE=$(echo $line | cut -d ':' -f 2)
            NBR=$(echo $line | cut -d ':' -f 4)
            printf "::error::%s coding style error: %s#L%s\n%s\n" "$TYPE" "$NAME" "$LINE" "$NBR"
          done
      - name: continue
        run: |
          if [ -s coding-style-reports.log ]; then
            exit 1
          else
            exit 0
          fi

  check_program_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout-v4
        uses: actions/checkout@v4
      - name: run-compilation
        run: make
        timeout-minutes: 2
      - name: run-clean
        run: |
          make clean
      - name: check-executables
        run: |
          for file in $EXECUTABLES; do
            if [ ! -x "$file" ]; then
              echo "$file does not exist or is not executable"
              exit 1
            fi
          done
          exit 0

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout-v4
        uses: actions/checkout@v4
      - name: run-tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout-v4
        uses: actions/checkout@v4
      - name: mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
